##############################
# SECURONIX - CENTOS 6
# Formato NXLog-like (JSON)
##############################

# Inputs
$ModLoad imuxsock
$ModLoad imklog

##############################
# Template NXLog Style
##############################
$template SecuronixNXLog,"<%pri%>%timegenerated% %hostname% {\"EventReceivedTime\":\"%timegenerated:::date-mysql%\",\"SourceModuleName\":\"rsyslog\",\"SourceModuleType\":\"imuxsock\",\"SyslogFacilityValue\":%syslogfacility%,\"SyslogFacility\":\"%syslogfacility-text%\",\"SyslogSeverityValue\":%syslogseverity%,\"SyslogSeverity\":\"%syslogseverity-text%\",\"SeverityValue\":%syslogseverity%,\"Severity\":\"%syslogseverity-text%\",\"Hostname\":\"%hostname%\",\"EventTime\":\"%timegenerated:::date-mysql%\",\"SourceName\":\"%programname%\",\"ProcessID\":\"%procid%\",\"Message\":\"%msg%\"}\n"

##############################
# Envio para Securonix (UDP)
##############################
*.* @172.18.16.5:6515;SecuronixNXLog

