# Template JSON para logs Sysmon
template(name="SysmonToJSON" type="string" string="{\"program\":\"%programname%\",\"timestamp\":\"%timegenerated:::date-rfc3339%\",\"hostname\":\"%HOSTNAME%\",\"message\":\"%msg%\"}\n")

# Encaminhar logs do Sysmon ao Securonix Collector
if $programname == 'sysmon' then {
    action(
        type="omfwd"
        Target="172.18.16.4"
        Port="514"
        Protocol="udp"
        Template="SysmonToJSON"
    )
    stop
}
