# === REGRA DE ENVIO PARA SECURONIX ===
# Envia logs do Sysmon em formato JSON via TCP para o servidor Securonix
template(name="json" type="string" string="<%syslogpriority%> %timegenerated% %HOSTNAME% msg=%jsonmesg%\n") action(type="omfwd" Target="172.18.16.5" Port="6515" Protocol="udp" Device="ens32" template="json")

if $programname == 'sysmon' then @@172.18.16.5:6515;SysmonToJSON
& stop   # Impede duplicação dos logs no armazenamento local
