define ROOT /usr
define CERTDIR %ROOT%/cert
define LOGFILE /var/log/nxlog/nxlog.log

Moduledir %ROOT%/lib/nxlog/modules
CacheDir /var/spool/nxlog/data
PidFile /var/run/nxlog/nxlog.pid
LogFile %LOGFILE%
LogLevel INFO

<Extension _syslog>
    Module            xm_syslog
</Extension>

<Extension _json>
    Module            xm_json
</Extension>

#<Extension _xml>
#    Module            xm_xml
#    PrefixWinEvent    TRUE
#</Extension>

<Input sysmon>
    Module im_file
    File '/var/log/messages'
    <Exec>
        if $raw_event !~ /Sysmon/ drop();
        parse_syslog();
        to_json();
    </Exec>
</Input>


<Output output_file>
    Module            om_file
    File              '/tmp/output.json'
    <Exec>
        parse_syslog();
        #parse_windows_eventlog_xml($Message);
        to_json();
    </Exec>
</Output>

<Output securonix_out>
    Module om_udp
    Host 192.168.122.214
    Port 514
</Output>

<Route sysmon_to_securonix>
    Path sysmon => output_file, securonix_out
</Route>

